#!/usr/bin/env python3
"""
Combine one or more StatisticalEvaluator JSON files and perform:

1. boxplot generation
2. two-way ANOVA with system and query as factors
3. Tukey HSD post-hoc pairwise comparisons using the same qids/topics
   as complete blocks

The script expects JSON files produced by `unipd.se.StatisticalEvaluator`.

Example:
    python3 code/py/anova_tukey_boxplot.py \
      --inputs \
        results/statistics/nemotron_top100_baseline_en_dev.json \
        results/statistics/nemotron_top1000_baseline_en_dev.json \
        results/statistics/nemotron_lora_top1000_en_dev.json \
      --metric mrr5 \
      --outdir results/statistics/en_dev_mrr5 \
      --title "English DEV - MRR@5"
"""

from __future__ import annotations

import argparse
import csv
from itertools import combinations
import json
import math
import statistics
from pathlib import Path
from typing import Iterable


METRIC_TO_JSON_KEY = {
    "mrr5": "mrr@5",
    "ndcg10": "ndcg@10",
    "ap": "ap",
}

INSTALL_HINT = "python3 -m pip install pandas matplotlib statsmodels scipy"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run boxplot + blocked two-way ANOVA + blocked Tukey HSD "
            "on per-query evaluation JSON files."
        )
    )
    parser.add_argument(
        "--inputs",
        nargs="+",
        required=True,
        help="One or more JSON files generated by unipd.se.StatisticalEvaluator.",
    )
    parser.add_argument(
        "--metric",
        choices=sorted(METRIC_TO_JSON_KEY),
        default="mrr5",
        help="Per-query metric to analyze.",
    )
    parser.add_argument(
        "--outdir",
        required=True,
        help="Directory where CSV, plots, and statistical outputs will be written.",
    )
    parser.add_argument(
        "--title",
        default=None,
        help="Optional chart title. If omitted, a sensible default is used.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help="Significance level for Tukey HSD.",
    )
    return parser.parse_args()


def require_dependency(module_name: str, install_hint: str) -> None:
    try:
        __import__(module_name)
    except ImportError as exc:
        raise SystemExit(
            f"Missing Python dependency '{module_name}'. Install it with:\n{install_hint}"
        ) from exc


def load_rows(path: Path, json_metric_key: str) -> list[dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    metadata = payload.get("metadata", {})
    per_query = payload.get("per_query", [])

    system_name = metadata.get("system") or path.stem
    rows = []
    for item in per_query:
        rows.append(
            {
                "qid": str(item["qid"]),
                "system": system_name,
                "score": float(item[json_metric_key]),
                "rank": int(item.get("first_relevant_rank", -1)),
            }
        )
    return rows


def validate_same_query_set(rows: list[dict]) -> None:
    systems = sorted({row["system"] for row in rows})
    qids_by_system = {
        system: {row["qid"] for row in rows if row["system"] == system}
        for system in systems
    }

    first_system = systems[0]
    reference = qids_by_system[first_system]
    for system in systems[1:]:
        if qids_by_system[system] != reference:
            missing = sorted(reference - qids_by_system[system])[:10]
            extra = sorted(qids_by_system[system] - reference)[:10]
            raise SystemExit(
                "The selected runs do not share the same qid set.\n"
                f"Reference system: {first_system} ({len(reference)} qids)\n"
                f"Offending system: {system} ({len(qids_by_system[system])} qids)\n"
                f"Missing sample: {missing}\n"
                f"Extra sample: {extra}"
            )


def write_long_csv(rows: list[dict], out_csv: Path) -> None:
    with out_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["qid", "system", "score", "rank"])
        writer.writeheader()
        writer.writerows(rows)


def write_summary_csv(rows: list[dict], out_csv: Path) -> None:
    grouped: dict[str, list[float]] = {}
    for row in rows:
        grouped.setdefault(row["system"], []).append(row["score"])

    with out_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["system", "queries", "mean", "median", "std_dev", "min", "max"])
        for system, values in sorted(grouped.items()):
            writer.writerow(
                [
                    system,
                    len(values),
                    statistics.fmean(values),
                    statistics.median(values),
                    statistics.stdev(values) if len(values) > 1 else 0.0,
                    min(values),
                    max(values),
                ]
            )


def build_boxplot(rows: list[dict], out_png: Path, title: str, metric_label: str) -> None:
    import matplotlib.pyplot as plt
    import pandas as pd

    df = pd.DataFrame(rows)
    order = list(dict.fromkeys(df["system"].tolist()))
    data = [df.loc[df["system"] == system, "score"].tolist() for system in order]

    fig, ax = plt.subplots(figsize=(13, 8))
    ax.boxplot(
        data,
        patch_artist=True,
        widths=0.46,
        whis=1.5,
        boxprops={
            "facecolor": "white",
            "edgecolor": "#4d4d4d",
            "linewidth": 1.4,
        },
        whiskerprops={
            "color": "#4d4d4d",
            "linewidth": 1.4,
        },
        capprops={
            "color": "#4d4d4d",
            "linewidth": 1.4,
        },
        medianprops={
            "color": "#ff8c1a",
            "linewidth": 1.6,
        },
        flierprops={
            "marker": "o",
            "markerfacecolor": "white",
            "markeredgecolor": "black",
            "markeredgewidth": 1.2,
            "markersize": 7,
            "linestyle": "none",
        },
    )

    ax.set_title(title, fontsize=19, pad=12)
    ax.set_xlabel("Systems", fontsize=15)
    ax.set_ylabel(f"{metric_label.lower()} values", fontsize=15)
    ax.set_xticks(range(1, len(order) + 1))
    ax.set_xticklabels(order, rotation=0, ha="center", fontsize=11)
    ax.tick_params(axis="y", labelsize=11)
    ax.set_facecolor("white")
    ax.grid(axis="y", linestyle=":", linewidth=1.0, color="#bdbdbd", alpha=0.9)
    ax.set_axisbelow(True)

    for spine in ax.spines.values():
        spine.set_linewidth(1.0)
        spine.set_color("black")

    fig.patch.set_facecolor("white")
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close()


def run_anova(rows: list[dict], out_csv: Path) -> dict:
    import pandas as pd
    import statsmodels.api as sm
    from statsmodels.formula.api import ols

    df = pd.DataFrame(rows)
    model = ols("score ~ C(system) + C(qid)", data=df).fit()
    table = sm.stats.anova_lm(model, typ=2)
    table.to_csv(out_csv)

    system_row = table.loc["C(system)"]
    residual_row = table.loc["Residual"]
    system_order = list(dict.fromkeys(df["system"].tolist()))
    means = (
        df.groupby("system", sort=False)["score"]
        .mean()
        .reindex(system_order)
        .to_dict()
    )

    return {
        "sum_sq": float(system_row["sum_sq"]),
        "df": float(system_row["df"]),
        "f": float(system_row["F"]),
        "p_value": float(system_row["PR(>F)"]),
        "mse": float(residual_row["sum_sq"] / residual_row["df"]),
        "df_error": float(residual_row["df"]),
        "blocks": int(df["qid"].nunique()),
        "system_count": int(df["system"].nunique()),
        "system_order": system_order,
        "system_means": means,
    }


def run_tukey(
    rows: list[dict], alpha: float, out_csv: Path, anova_summary: dict
) -> list[dict]:
    from scipy.stats import studentized_range

    systems = list(anova_summary["system_order"])
    system_means = dict(anova_summary["system_means"])
    mse = float(anova_summary["mse"])
    df_error = float(anova_summary["df_error"])
    blocks = int(anova_summary["blocks"])
    system_count = int(anova_summary["system_count"])

    if blocks <= 0:
        raise SystemExit("Blocked Tukey HSD requires at least one shared qid.")
    if df_error <= 0:
        raise SystemExit("Blocked Tukey HSD requires a positive residual degrees of freedom.")

    std_error = math.sqrt(mse / blocks)
    q_crit = float(studentized_range.ppf(1.0 - alpha, system_count, df_error))
    margin = q_crit * std_error
    results = []
    with out_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        header = [
            "group1",
            "group2",
            "meandiff",
            "p_adj",
            "lower",
            "upper",
            "reject",
            "std_error",
            "q_stat",
            "mse",
            "blocks",
            "df_error",
            "q_crit",
            "method",
        ]
        writer.writerow(header)

        for group1, group2 in combinations(systems, 2):
            diff = float(system_means[group2] - system_means[group1])
            q_stat = abs(diff) / std_error if std_error > 0 else math.inf
            p_adj = float(studentized_range.sf(q_stat, system_count, df_error))
            lower = diff - margin
            upper = diff + margin
            reject = abs(diff) > margin

            row = [
                group1,
                group2,
                diff,
                p_adj,
                lower,
                upper,
                reject,
                std_error,
                q_stat,
                mse,
                blocks,
                df_error,
                q_crit,
                "blocked_tukey_hsd",
            ]
            writer.writerow(row)
            results.append(
                {
                    "group1": group1,
                    "group2": group2,
                    "meandiff": diff,
                    "p_adj": p_adj,
                    "lower": lower,
                    "upper": upper,
                    "reject": reject,
                    "std_error": std_error,
                    "q_stat": q_stat,
                }
            )
    return results


def format_float(value: float) -> str:
    if math.isfinite(value):
        return f"{value:.6f}"
    return str(value)


def write_report(
    out_txt: Path,
    metric_name: str,
    title: str,
    anova_summary: dict,
    tukey_rows: Iterable[dict],
) -> None:
    lines = [
        title,
        "",
        f"Metric: {metric_name}",
        "",
        "ANOVA (system effect):",
        f"  sum_sq = {format_float(anova_summary['sum_sq'])}",
        f"  df     = {format_float(anova_summary['df'])}",
        f"  F      = {format_float(anova_summary['f'])}",
        f"  p      = {format_float(anova_summary['p_value'])}",
        "",
        "Blocked Tukey HSD pairwise comparisons:",
        "  The same qids/topics are treated as complete blocks, using the",
        "  residual MSE from the two-way ANOVA and the common number of blocks.",
    ]

    significant = False
    for row in tukey_rows:
        lines.append(
            "  "
            f"{row['group1']} vs {row['group2']} | "
            f"diff={format_float(row['meandiff'])} | "
            f"p_adj={format_float(row['p_adj'])} | "
            f"CI=[{format_float(row['lower'])}, {format_float(row['upper'])}] | "
            f"reject={row['reject']}"
        )
        significant = significant or row["reject"]

    if not significant:
        lines.append("  No pairwise comparison was significant at the chosen alpha.")

    out_txt.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()

    require_dependency(
        "pandas",
        INSTALL_HINT,
    )
    require_dependency(
        "matplotlib",
        INSTALL_HINT,
    )
    require_dependency(
        "statsmodels",
        INSTALL_HINT,
    )
    require_dependency(
        "scipy",
        INSTALL_HINT,
    )

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    json_metric_key = METRIC_TO_JSON_KEY[args.metric]
    rows: list[dict] = []
    for input_path in args.inputs:
        rows.extend(load_rows(Path(input_path), json_metric_key))

    if not rows:
        raise SystemExit("No per-query rows were found in the provided JSON files.")

    validate_same_query_set(rows)

    metric_label = {
        "mrr5": "MRR@5",
        "ndcg10": "nDCG@10",
        "ap": "AP",
    }[args.metric]
    title = args.title or f"System comparison on {metric_label}"

    long_csv = outdir / f"{args.metric}_per_query_long.csv"
    summary_csv = outdir / f"{args.metric}_summary.csv"
    boxplot_png = outdir / f"{args.metric}_boxplot.png"
    anova_csv = outdir / f"{args.metric}_anova.csv"
    tukey_csv = outdir / f"{args.metric}_tukey.csv"
    report_txt = outdir / f"{args.metric}_report.txt"

    write_long_csv(rows, long_csv)
    write_summary_csv(rows, summary_csv)
    build_boxplot(rows, boxplot_png, title, metric_label)
    anova_summary = run_anova(rows, anova_csv)
    tukey_rows = run_tukey(rows, args.alpha, tukey_csv, anova_summary)
    write_report(report_txt, metric_label, title, anova_summary, tukey_rows)

    print(f"Saved long-form scores to: {long_csv}")
    print(f"Saved summary table to:   {summary_csv}")
    print(f"Saved boxplot to:         {boxplot_png}")
    print(f"Saved ANOVA table to:     {anova_csv}")
    print(f"Saved Tukey HSD to:       {tukey_csv}")
    print(f"Saved text report to:     {report_txt}")


if __name__ == "__main__":
    main()
